"""
Report service for downloadable Markdown and PDF reports.
"""

import math
import re

from fpdf import FPDF


def _strip_inline_markdown(text: str) -> str:
    """Remove inline markdown while keeping readable text."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"`(.*?)`", r"\1", text)
    text = re.sub(r"\[(.*?)\]\((.*?)\)", r"\1", text)
    return text.strip()


def _safe_text(text: str) -> str:
    """Encode text safely for fpdf2."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _format_value(value) -> str:
    """Format statistical values for a report."""
    if value is None:
        return "N/A"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, float):
        if math.isnan(value) or math.isinf(value):
            return "N/A"
        if value.is_integer():
            return f"{int(value):,}"
        return f"{value:,.2f}"
    return str(value)


def _numeric_summary_line(column_name: str, values: dict) -> str:
    return (
        f"{column_name}: average {_format_value(values.get('mean'))}, "
        f"median {_format_value(values.get('50%'))}, "
        f"range {_format_value(values.get('min'))} to {_format_value(values.get('max'))}, "
        f"standard deviation {_format_value(values.get('std'))}."
    )


def _categorical_summary_line(column_name: str, values: dict) -> str:
    top = _format_value(values.get("top"))
    freq = _format_value(values.get("freq"))
    unique = _format_value(values.get("unique"))
    return (
        f"{column_name}: {unique} unique values. "
        f"The most common value is '{top}', appearing {freq} times."
    )


def generate_markdown_report(
    summary_text: str,
    stats: dict,
    insights: str,
    report_content: str,
) -> str:
    """Build a full Markdown report string."""
    lines = [
        "# GenAI Data Analysis Report\n",
        "---\n",
        "## Dataset Summary\n",
        summary_text,
        "\n---\n",
        "## AI Insights\n",
        insights,
        "\n---\n",
        "## Full Analysis Report\n",
        report_content,
        "\n---\n",
        "*Generated by GenAI Data Analyst*",
    ]
    return "\n".join(lines)


class _ReportPDF(FPDF):
    """Custom PDF renderer with readable report styling."""

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "GenAI Data Analysis Report", align="R")
        self.ln(4)
        self.set_draw_color(99, 102, 241)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(140, 140, 140)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(99, 102, 241)
        self.cell(0, 10, _safe_text(title))
        self.ln(8)
        self.set_draw_color(99, 102, 241)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.ln(4)

    def subsection_title(self, title: str):
        self.ln(2)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(55, 65, 81)
        self.multi_cell(0, 6, _safe_text(title))
        self.ln(1)

    def paragraph(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, _safe_text(text))
        self.ln(1)

    def bullet(self, text: str):
        left = self.l_margin + 4
        self.set_x(left)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.cell(5, 6, "-", new_x="RIGHT", new_y="TOP")
        self.multi_cell(self.w - self.r_margin - self.get_x(), 6, _safe_text(text))
        self.ln(0.5)

    def render_markdown(self, text: str):
        """Render basic markdown structure as readable PDF content."""
        for raw_line in text.splitlines():
            line = raw_line.strip()
            if not line:
                self.ln(2)
                continue

            if line.startswith("### "):
                self.subsection_title(_strip_inline_markdown(line[4:]))
                continue
            if line.startswith("## "):
                self.subsection_title(_strip_inline_markdown(line[3:]))
                continue
            if line.startswith("# "):
                self.subsection_title(_strip_inline_markdown(line[2:]))
                continue
            if re.match(r"^[-*]\s+", line):
                self.bullet(_strip_inline_markdown(re.sub(r"^[-*]\s+", "", line)))
                continue
            if re.match(r"^\d+\.\s+", line):
                self.bullet(_strip_inline_markdown(re.sub(r"^\d+\.\s+", "", line)))
                continue

            self.paragraph(_strip_inline_markdown(line))


def _render_key_statistics(pdf: _ReportPDF, stats: dict):
    """Render stats as concise report prose instead of raw dumps."""
    if not stats:
        return

    pdf.section_title("Key Statistics")

    numeric_stats = stats.get("numeric") or {}
    categorical_stats = stats.get("categorical") or {}

    if numeric_stats:
        pdf.subsection_title("Numeric metrics")
        for column_name, values in numeric_stats.items():
            if isinstance(values, dict):
                pdf.bullet(_numeric_summary_line(column_name, values))

    if categorical_stats:
        pdf.subsection_title("Categorical metrics")
        for column_name, values in categorical_stats.items():
            if isinstance(values, dict):
                pdf.bullet(_categorical_summary_line(column_name, values))


def generate_pdf_report(
    summary_text: str,
    stats: dict,
    insights: str,
    report_content: str,
) -> bytes:
    """Build a formatted PDF report and return the raw bytes."""
    pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(99, 102, 241)
    pdf.ln(20)
    pdf.cell(0, 14, "GenAI Data Analysis Report", align="C")
    pdf.ln(14)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 8, "Powered by AI | Automated Insights", align="C")
    pdf.ln(18)

    pdf.section_title("Dataset Summary")
    pdf.render_markdown(summary_text)

    _render_key_statistics(pdf, stats)

    pdf.section_title("AI Insights")
    pdf.render_markdown(insights)

    pdf.section_title("Full Analysis Report")
    pdf.render_markdown(report_content)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(140, 140, 140)
    pdf.cell(0, 8, "Generated by GenAI Data Analyst", align="C")

    return bytes(pdf.output())
